const NOTES_SUCCESS = 'NOTES_SUCCESS'
const ADD_NOTE = 'ADD_NOTE'
const EDIT_NOTE = 'EDIT_NOTE'
const REMOVE_NOTE = 'REMOVE_NOTE'

const FETCH_NOTES_REQUEST = 'FETCH_REQUEST'
const FETCH_NOTES_SUCCESS = 'FETCH_SUCCESS'
const FETCH_NOTES_FAILURE = 'FETCH_FAILURE'

export {
	NOTES_SUCCESS,
	ADD_NOTE,
	EDIT_NOTE,
	REMOVE_NOTE,
	FETCH_NOTES_REQUEST,
	FETCH_NOTES_SUCCESS,
	FETCH_NOTES_FAILURE,
}
